### ISSUE TITLE
My name listed in a fully open repo.

### ISSUE THREAD

**Issue by jarandmi** [digipost/digipost-api-client-dotnet#141]
https://github.com/digipost/digipost-api-client-dotnet/blob/2899eb0c566165422c7c908155c4765a0c1bb600/Digipost.Api.Client.Resources/Xml/Data/SearchResult.xml#L31

Why is my name listed here in a fully open repo? I don't think this file should be here.

**Comment by asjafjell** [comment]
Hi, Jarand! 

I am sorry that you are getting a response so late - this is due to the easter holidays, and we are all on vacation. 

I agree, this should not happen. I have now created a pull request to remove your name from the current version of the file. This is just a temporary measure, and as much as I can do with my permissions.

As soon as easter holidays are over, we will remove your name, including this thread.

Thank you for informing us. We will look into why this happened and make sure it does not happen again.

**Comment by asjafjell** [comment]
Hi again! It has taken some time for GIthub to remove the sensitive data, but all references to the file is now removed. Please let me know if this is not the case or you have other questions. Marking this issue as closed.

Thanks!
